<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishTrimmed>true</PublishTrimmed>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PackageId>LambdaKit.Terminal</PackageId>
    <Version>5.0.3</Version>
    <Authors>0xDED</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>LambdaKit;terminal;library;color;console;ansi;argparser;window</PackageTags>
    <PackageDescription>LambdaKit.Terminal is a C# library for managing everything in the terminal, it's an alternative of Console, and it can be used for tui applications.</PackageDescription>
    <RepositoryUrl>https://github.com/dedouwe26/LambdaKit.Terminal.git</RepositoryUrl>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.ILLink.Tasks" Version="8.0.22" />
    <None Include="../README.md" Pack="true" PackagePath="/"/>
  </ItemGroup>
  <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('Windows'))">
    <DefineConstants>OS_WINDOWS</DefineConstants>
  </PropertyGroup>
  <PropertyGroup>
    <DocumentationFile>bin/$(Configuration)/$(TargetFramework)/$(AssemblyName).xml</DocumentationFile>
  </PropertyGroup>
</Project>
